version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth_service
    ports:
      - "8000:8000"
    volumes:
      - ./auth-service:/app
    env_file:
      - .env
    restart: always
